services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-dev
    image: server-dev
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=${profile}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - IP=${IP}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWT_ACCESS_SECRET_BASE64=${JWT_ACCESS_SECRET_BASE64}
      - JWT_REFRESH_SECRET_BASE64=${JWT_REFRESH_SECRET_BASE64}
      - ANDROID_JH=${ANDROID_JH}
      - ANDROID_MH=${ANDROID_MH}
      - ANDROID_SW=${ANDROID_SW}
      - SERVER_YR=${SERVER_YR}
      - SERVER_MASTER=${SERVER_MASTER}
      - KID_AUTH_SECRET=${KID_AUTH_SECRET}
    networks:
      - temp

networks:
  temp:
    driver: bridge
