spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: user
    password:

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: KUITKACHikariCP

  h2:
    console:
      enabled: true # H2 웹 콘솔 활성화
      path: /h2-console # H2 웹 콘솔 접근 경로

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영 배포 시 none + Flyway 권장
    show-sql: true # 운영 배포 시 false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      platform: h2

  docker:
    compose:
      enabled: false

logging:
  level:
    root: INFO # 기본 로그 레벨
    org.springframework.web: INFO # Spring Web 관련 로그
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 (개발 시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 로그 (개발 시)