server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: KUITKAC_HikariCP

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 운영 배포 시 none + Flyway 권장
    show-sql: true # 운영 배포 시 false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always # 애플리케이션 시작 시 항상 schema.sql과 data.sql 실행
      continue-on-error: true # 스크립트 실행 중 오류 발생 시에도 계속 진행할지 여부 (개발 시 유용)
      platform: mysql # 사용하는 DB 플랫폼 명시 (선택 사항이지만 명확하게 해줌)

  docker:
    compose:
      enabled: false

logging:
  level:
    root: INFO # 기본 로그 레벨
    org.springframework.web: INFO # Spring Web 관련 로그
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 (개발 시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 로그 (개발 시)