spring:
  profiles:
    active: local

  application:
    name: KUIT_KAC

springdoc:
  packages-to-scan: org.example.kuit_kac

server:
  port: 8080

logging:
  level:
    root: INFO # 기본 로그 레벨
    org.springframework.web: INFO # Spring Web 관련 로그
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 (개발 시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 로그 (개발 시)