spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: KUITKAC_HikariCP

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # 운영 배포 시 none + Flyway 권장
    show-sql: true # 운영 배포 시 false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
client-id: "<REMOVED>"# 외부 노출 금지
client-secret: "<REMOVED>"            #            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 테스트용
            # 프론트 테스트시
            # http://localhost:8080/oauth2/authorization/kakao
            client-authentication-method: client_secret_post
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  docker:
    compose:
      enabled: false

jwt:
jwt.secret-base64: "<REMOVED>"  access-ttl-ms: 1800000 # 30분
  refresh-ttl-ms: 1209600000 #14일

logging:
  level:
    root: INFO # 기본 로그 레벨
    org.springframework.web: INFO # Spring Web 관련 로그
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 (개발 시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 로그 (개발 시)

#frontend:
#  redirect:
#    url: "http://localhost:3000/oauth2-redirect.html"

