spring:
  profiles:
    active: local

  application:
    name: KUIT_KAC

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 69881949b9b10ec2a0bd9a562f85566f # 외부 노출 금지
            client-secret: NRi5v7dXMKgYeobijYJ8YKMtiB3MJQny
            redirect-uri: "localhost:8080/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao

        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  packages-to-scan: org.example.kuit_kac

server:
  port: 8080

logging:
  level:
    root: INFO # 기본 로그 레벨
    org.springframework.web: INFO # Spring Web 관련 로그
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 (개발 시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 로그 (개발 시)