spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: KUITKAC_HikariCP

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # 운영 배포 시 none + Flyway 권장
    show-sql: true # 운영 배포 시 false
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      enabled: false

jwt:
  access-secret-base64: ${JWT_ACCESS_SECRET_BASE64}
  refresh-secret-base64: ${JWT_REFRESH_SECRET_BASE64}
  access-ttl-ms: 1800000 # 30분
  refresh-ttl-ms: 1209600000 #14일

auth:
  login:
    success:
      mode: DEEPLINK # JSON | DEEPLINK
      deep-link: myapp://oauth/kakao # 임시
      access-param: access
      refresh-param: refresh
      expires-param: expires-in
      state-param: state
      onboarding-required: onboarding-required
      access-ttl-seconds: 1800
  onboarding:
    require: false # TODO 임시우회(나중에 true로 바꿔야 함)

logging:
  level:
    root: INFO # 기본 로그 레벨
    org.springframework.web: INFO # Spring Web 관련 로그
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 (개발 시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 로그 (개발 시)

debug:
  kid-auth:
    enabled: true
    secret: ${KID_AUTH_SECRET}
    ts-skew-seconds: 300
    whitelist:
      enabled: false
      kids:
        - ${ANDROID_MH}
        - ${ANDROID_SW}
        - ${ANDROID_JH}
        - ${SERVER_YR}
        - ${SERVER_MASTER}

  onboarding:
    autofill:
      enabled: false
      default-gender: MALE  # GenderType
      default-age: 25
      default-height: 170
      default-target-weight: 65.0
