package org.example.kuit_kac.domain.food.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum FoodType {
    NORMAL_GRAIN_AND_TUBER("NORMAL_GRAIN_AND_TUBER", "곡류, 서류 제품"),
    NORMAL_FRUIT("NORMAL_FRUIT", "과일류"),
    NORMAL_GRILLED("NORMAL_GRILLED", "구이류"),
    NORMAL_SOUP_AND_TANG("NORMAL_SOUP_AND_TANG", "국 및 탕류"),
    NORMAL_KIMCHI("NORMAL_KIMCHI", "김치류"),
    NORMAL_NAMUL_AND_SUKCHAE("NORMAL_NAMUL_AND_SUKCHAE", "나물·숙채류"),
    NORMAL_BEANS_AND_NUTS("NORMAL_BEANS_AND_NUTS", "두류, 견과 및 종실류"),
    NORMAL_NOODLE_AND_DUMPLING("NORMAL_NOODLE_AND_DUMPLING", "면 및 만두류"),
    NORMAL_RICE("NORMAL_RICE", "밥류"),
    NORMAL_STIR_FRIED("NORMAL_STIR_FRIED", "볶음류"),
    NORMAL_BREAD_AND_SNACK("NORMAL_BREAD_AND_SNACK", "빵 및 과자류"),
    NORMAL_FRESH_AND_MUCHIM("NORMAL_FRESH_AND_MUCHIM", "생채·무침류"),
    NORMAL_FISH_AND_MEAT("NORMAL_FISH_AND_MEAT", "수·조·어·육류"),
    NORMAL_DAIRY_AND_ICECREAM("NORMAL_DAIRY_AND_ICECREAM", "유제품류 및 빙과류"),
    NORMAL_BEVERAGE_AND_TEA("NORMAL_BEVERAGE_AND_TEA", "음료 및 차류"),
    NORMAL_SAUCE_AND_SEASONING("NORMAL_SAUCE_AND_SEASONING", "장류, 양념류"),
    NORMAL_PICKLE("NORMAL_PICKLE", "장아찌·절임류"),
    NORMAL_PANCAKE("NORMAL_PANCAKE", "전·적 및 부침류"),
    NORMAL_SALTED_SEAFOOD("NORMAL_SALTED_SEAFOOD", "젓갈류"),
    NORMAL_BRAISED("NORMAL_BRAISED", "조림류"),
    NORMAL_PORRIDGE_AND_SOUP("NORMAL_PORRIDGE_AND_SOUP", "죽 및 스프류"),
    NORMAL_STEW_AND_HOT_POT("NORMAL_STEW_AND_HOT_POT", "찌개 및 전골류"),
    NORMAL_STEAMED("NORMAL_STEAMED", "찜류"),
    NORMAL_VEGETABLE_AND_SEAWEED("NORMAL_VEGETABLE_AND_SEAWEED", "채소, 해조류"),
    NORMAL_FRIED("NORMAL_FRIED", "튀김류"),
    
    // 가공식품류
    PROCESSED_BREAD_AND_SNACK("PROCESSED_BREAD_AND_SNACK", "과자류, 빵류 또는 떡류"),
    PROCESSED_OTHER_FOOD("PROCESSED_OTHER_FOOD", "기타식품류"),
    PROCESSED_AGRICULTURAL("PROCESSED_AGRICULTURAL", "농산가공식품류"),
    PROCESSED_SUGAR("PROCESSED_SUGAR", "당류"),
    PROCESSED_ANIMAL("PROCESSED_ANIMAL", "동물성가공식품류"),
    PROCESSED_TOFU_AND_MUK("PROCESSED_TOFU_AND_MUK", "두부류 또는 묵류"),
    PROCESSED_NOODLE("PROCESSED_NOODLE", "면류"),
    PROCESSED_ICECREAM("PROCESSED_ICECREAM", "빙과류"),
    PROCESSED_SEAFOOD("PROCESSED_SEAFOOD", "수산가공식품류"),
    PROCESSED_OIL("PROCESSED_OIL", "식용유지류"),
    PROCESSED_MEAT("PROCESSED_MEAT", "식육가공품 및 포장육"),
    PROCESSED_EGG("PROCESSED_EGG", "알가공품류"),
    PROCESSED_DAIRY("PROCESSED_DAIRY", "유가공품류"),
    PROCESSED_BEVERAGE("PROCESSED_BEVERAGE", "음료류"),
    PROCESSED_SAUCE("PROCESSED_SAUCE", "장류"),
    PROCESSED_JAM("PROCESSED_JAM", "잼류"),
    PROCESSED_PICKLE_AND_BRAISED("PROCESSED_PICKLE_AND_BRAISED", "절임류 또는 조림류"),
    PROCESSED_SEASONING("PROCESSED_SEASONING", "조미식품"),
    PROCESSED_ALCOHOL("PROCESSED_ALCOHOL", "주류"),
    PROCESSED_INSTANT("PROCESSED_INSTANT", "즉석식품류"),
    PROCESSED_COCOA_CHOCOLATE("PROCESSED_COCOA_CHOCOLATE", "코코아가공품 또는 초콜릿류"),
    PROCESSED_NUTRITION("PROCESSED_NUTRITION", "특수영양식품"),
    PROCESSED_MEDICAL("PROCESSED_MEDICAL", "특수의료용도식품");

    private final String value;
    private final String koreanName;
} 